django-hello/hello/urls.py
from django.urls import path

from . import views

app_name = 'hello'

urlpatterns = [
    path('', views.HelloView.as_view(), name='hello'),
    # path('', views.hello, name='hello'),
    path('specifics/<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('specifics/<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

sample/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
#import hello.views

urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#   url(r'^hello/', hello.views.hello),
    path('hello/', include('hello.urls')),
    path('admin/', admin.site.urls),
]

django-hello/hello/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django-hello/hello/views.py
from django.http import HttpResponseRedirect
#from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

#def hello(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    #template = loader.get_template('hello/hello.html')
#    context = {
#            'latest_question_list': latest_question_list,
#    }
#    #return HttpResponse(template.render(context, request))
#    return render(request, 'hello/hello.html', context)
class HelloView(generic.ListView):
    template_name = 'hello/hello.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'hello/detail.html', {'question': question})
class DetailView(generic.DetailView):
    model = Question
    template_name = 'hello/detail.html'

#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'hello/results.html', {'question': question})
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'hello/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'hello/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice .",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('hello:results', args=(question.id,)))

django-hello/hello/templates/hello/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hello:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

django-hello/hello/templates/hello/hello.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'hello:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django-hello/hello/templates/hello/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'hello:detail' question.id %}">Vote again?</a>